### ISSUE TITLE
llava-phi3 support

### ISSUE THREAD

**Issue by XxxZzD** [wangclnlp/Vision-LLM-Alignment#2]
Due to my limited resources, I have found it challenging to work with Llama3 and other versions of Llava.I have recently trained a Llava-phi3 model from https://github.com/mbzuai-oryx/LLaVA-pp. I am interested in knowing if it is feasible to use your code to conduct reinforcement learning training with my trained model.
Your guidance and assistance in this matter would be greatly appreciated.

**Comment by wangclnlp** [comment]
Thank you for your attention! It seems that this is not a regular model architecture. However, after conducting our research, we found that our system should easily support this model. Please contact me (email: clwang1119@gmail.com or wechat:wly12110519), and we can assist you in using our system to support the alignment training of this model.
