### ISSUE TITLE
cogvlm2 support

### ISSUE THREAD

**Issue by kaka-Cao** [wangclnlp/Vision-LLM-Alignment#3]
您好！最近基于cogvlm2多模态大模型训练了一个我们自己的垂类大模型，想在SFT之后进行强化学习训练，不知道此仓库是否支持cogvlm2的DPO训练，或者能否和您交流如何实现这一目的。

**Comment by wangclnlp** [comment]
Thank you for your attention! Please contact me (email: [clwang1119@gmail.com](mailto:clwang1119@gmail.com) or wechat:wly12110519), and we could assist you in using our system to support the alignment training of this model.
